version: "3.9" # optional since v1.27.0
services:
 singlebox:
  platform: linux/amd64
  image: ghcr.io/cbajapan/cbala-base:main
  environment:
    - CLUSTER_ADDRESS
    - FAS_BIND_ADDRESS
    - ADMIN_USER
    - ADMIN_PASSWORD
    - JDK_PATH
    - FCSDK_PACKS
    - LA_PACKS
  ports:
   - "9999:9999"
   - "9990:9990"
   - "8080:8080"
   - "8443:8443"
   - "16000-16004:16000-16004/tcp"
   - "16000-16004:16000-16004/udp"
  volumes:
   - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
   - ./installer:/installsrc
  cap_add:
   - SYS_ADMIN
  networks:
    cbala_net:
     ipv4_address: ${FAS_BIND_ADDRESS}
  command: sh -c "chmod +x /installsrc/install-la-singlebox.sh && exec /installsrc/install-la-singlebox.sh"

networks:
 cbala_net:
  driver: bridge
  ipam:
   driver: default
   config:
     - subnet: ${DOCKER_NET}
       gateway: ${DOCKER_NET_GATEWAY}
